version: "2"

services:
  postgres:
    env_file:
      - ".env"
    image: "postgres:10.3-alpine"
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"

  web:
    build: "."
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "fakefacts.app:create_app()"
    depends_on:
      - "postgres"
    env_file:
      - ".env"
    ports:
      - "8000:8000"
    volumes:
      - ".:/app"

  factbot:
    build: "."
    command: fakefacts bot
    depends_on:
      - "postgres"
    env_file:
      - ".env"
    volumes:
      - ".:/app"

  simulate_users:
    build: "."
    command: fakefacts simulate_users
    depends_on:
      - "postgres"
    env_file:
      - ".env"
    volumes:
      - ".:/app"

volumes:
  postgres: {}
